fancybox: true ## If you want to use fancybox please set the value to true
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: haoflynet ## Your disqus_shortname, e.g. username
google_search: true ## Use Google search, true/false
baidu_search: ## Use Baidu search, true/false
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
google_analytics: UA-47480072-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
shareto: true ## If you want to use the share button please set the value to true

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
  - page: 我的收藏
    directory: favorites.html
    icon: icon-archive
  - page: 我的wiki
    directory: https://github.com/haoflynet/wiki
    icon: icon-archive
  - page: rss
    directory: atom.xml
    icon: icon-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - recent_posts
  - recent_comments
  - links

links:
  - title: 谢翔的Blog
    url: http://xiang.jwzcq.com/
  - title: Phodal
    url: https://www.phodal.com/
  - title: qingguo
    url: http://www.cnblogs.com/qingguo

# Static files
js: js
css: css

# Theme version
version: 0.0.0
